//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JxMobileWeb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARMAINRF
    {
        public long CREATEDATETIMERF { get; set; }
        public long UPDATEDATETIMERF { get; set; }
        public string ENTERPRISECODERF { get; set; }
        public System.Guid FILEHEADERGUIDRF { get; set; }
        public string UPDEMPLOYEECODERF { get; set; }
        public string UPDASSEMBLYID1RF { get; set; }
        public string UPDASSEMBLYID2RF { get; set; }
        public int LOGICALDELETECODERF { get; set; }
        public int CARMNGNORF { get; set; }
        public Nullable<int> NUMBERPLATE1CODERF { get; set; }
        public string NUMBERPLATE1NAMERF { get; set; }
        public string NUMBERPLATE2RF { get; set; }
        public string NUMBERPLATE3RF { get; set; }
        public Nullable<int> NUMBERPLATE4RF { get; set; }
        public Nullable<int> ENTRYDATERF { get; set; }
        public Nullable<int> FIRSTENTRYDATENUMTYPRF { get; set; }
        public Nullable<int> PRODUCETYPEOFYEARRF { get; set; }
        public Nullable<int> CARINSPECTYEARRF { get; set; }
        public Nullable<int> CUSTOMERCODERF { get; set; }
        public Nullable<int> CLAIMCODERF { get; set; }
        public string INPSECTIONCODERF { get; set; }
        public string MNGSECTIONCODERF { get; set; }
        public string SERVICESECTIONCDRF { get; set; }
        public Nullable<int> FEEGROUPCODERF { get; set; }
        public string FEEGROUPNAMERF { get; set; }
        public Nullable<int> FEEHEADERCODERF { get; set; }
        public string FEEHEADERNAMERF { get; set; }
        public byte[] MODEL12FULLMODELRF { get; set; }
        public Nullable<int> CARPROPERNORF { get; set; }
        public Nullable<int> FULLMODELFIXEDNO1RF { get; set; }
        public Nullable<int> FULLMODELFIXEDNO2RF { get; set; }
        public Nullable<int> FULLMODELFIXEDNO3RF { get; set; }
        public Nullable<int> FULLMODELFIXEDNO4RF { get; set; }
        public Nullable<int> FULLMODELFIXEDNO5RF { get; set; }
        public Nullable<int> FULLMODELFIXEDNO6RF { get; set; }
        public Nullable<int> FULLMODELFIXEDNO7RF { get; set; }
        public Nullable<int> FULLMODELFIXEDNO8RF { get; set; }
        public Nullable<int> FULLMODELFIXEDNO9RF { get; set; }
        public Nullable<int> FULLMODELFIXEDNO10RF { get; set; }
        public string FRAMENORF { get; set; }
        public byte[] FRAMEMODELRF { get; set; }
        public string CHASSISNORF { get; set; }
        public Nullable<int> CUSTOMIZECODERF { get; set; }
        public Nullable<int> CARADDITIONALINFO1CDRF { get; set; }
        public string CARADDITIONALINFO1NMRF { get; set; }
        public string CARNORF { get; set; }
        public Nullable<int> CHILDCODERF { get; set; }
        public string CHILDNAMERF { get; set; }
        public string COLORNORF { get; set; }
        public string TRIMNORF { get; set; }
        public string KEYNORF { get; set; }
        public Nullable<int> BOOKINDEXMAKERCDRF { get; set; }
        public Nullable<int> BOOKINDEXMODELCDRF { get; set; }
        public Nullable<int> BOOKINDEXMODELSUBCDRF { get; set; }
        public string BOOKINDEXMAKERNMRF { get; set; }
        public byte[] BOOKINDEXMODELNMRF { get; set; }
        public Nullable<long> SERIESCDRF { get; set; }
        public byte[] SERIESNMRF { get; set; }
        public Nullable<int> CARANALYSISCD1RF { get; set; }
        public Nullable<int> CARANALYSISCD2RF { get; set; }
        public Nullable<int> CARANALYSISCD3RF { get; set; }
        public Nullable<int> CARANALYSISCD4RF { get; set; }
        public Nullable<int> CARANALYSISCD5RF { get; set; }
        public Nullable<int> CARANALYSISCD6RF { get; set; }
        public Nullable<int> DMOUTPUTCONDITIONCDRF { get; set; }
        public Nullable<int> NEWUSEDCARCODERF { get; set; }
        public string NEWUSEDCARNAMERF { get; set; }
        public Nullable<int> PASSENBSINESCDRF { get; set; }
        public string PSSNGRBSINSSCDNMRF { get; set; }
        public Nullable<int> SALESLFOTHRMKRCDRF { get; set; }
        public string SALESLFOTHRMKRNMRF { get; set; }
        public Nullable<int> SELFOTHRMKRCDRF { get; set; }
        public string SELFOTHRMKRNMRF { get; set; }
        public Nullable<System.Guid> TAKEINIMAGEGROUPCDRF { get; set; }
        public Nullable<int> FIRSTTIMECIYEARRF { get; set; }
        public Nullable<int> FIRSTTIMECIMATDATERF { get; set; }
        public Nullable<int> EXCHSTDGROUPCDRF { get; set; }
        public Nullable<int> EXCHSTDCARDIVCODERF { get; set; }
        public Nullable<int> TRUSTCONTCARDIVCDRF { get; set; }
        public Nullable<int> CHECKCALCUNNCSRYCDRF { get; set; }
        public byte[] FULLMODELORORDERSIGNRF { get; set; }
        public string CARADDITIONALINFO3NMRF { get; set; }
        public Nullable<int> SUBSTCARUSEDIVCDRF { get; set; }
    }
}
