//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JxMobileWeb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARSPECRF
    {
        public long CREATEDATETIMERF { get; set; }
        public long UPDATEDATETIMERF { get; set; }
        public string ENTERPRISECODERF { get; set; }
        public System.Guid FILEHEADERGUIDRF { get; set; }
        public string UPDEMPLOYEECODERF { get; set; }
        public string UPDASSEMBLYID1RF { get; set; }
        public string UPDASSEMBLYID2RF { get; set; }
        public int LOGICALDELETECODERF { get; set; }
        public int CARMNGNORF { get; set; }
        public Nullable<int> MODELDESIGNATIONNORF { get; set; }
        public Nullable<int> CATEGORYNORF { get; set; }
        public Nullable<int> CARKINDCODERF { get; set; }
        public string CARKINDNAMERF { get; set; }
        public Nullable<int> CARPURPOSECODERF { get; set; }
        public string CARPURPOSENAMERF { get; set; }
        public Nullable<int> CARPRIVATEBUSINESSCDRF { get; set; }
        public string PRIVATEBUSINESSNMRF { get; set; }
        public Nullable<int> BODYSHAPECODERF { get; set; }
        public Nullable<int> AIRABODYSHAPECODERF { get; set; }
        public string BODYSHAPENAMERF { get; set; }
        public Nullable<int> DOMESTICFOREIGNCODERF { get; set; }
        public string DOMESTICFOREIGNNAMERF { get; set; }
        public Nullable<int> MAKERPARTSSRCHCODERF { get; set; }
        public Nullable<int> MAKERCODERF { get; set; }
        public Nullable<int> AIRAMAKERCODERF { get; set; }
        public string MAKERNAMERF { get; set; }
        public string AIRAMAKERNAMERF { get; set; }
        public Nullable<int> MODELCODERF { get; set; }
        public Nullable<int> MODELSUBCODERF { get; set; }
        public Nullable<int> SYSTEMATICCODERF { get; set; }
        public string SYSTEMATICNAMERF { get; set; }
        public Nullable<int> PRODUCETYPEOFYEARCDRF { get; set; }
        public string PRODUCETYPEOFYEARNMRF { get; set; }
        public Nullable<int> DOORCOUNTRF { get; set; }
        public Nullable<int> BODYNAMECODERF { get; set; }
        public string BODYNAMERF { get; set; }
        public Nullable<int> CHARACTERISTICCODERF { get; set; }
        public string CHARACTERISTICNAMERF { get; set; }
        public string MODELNAMERF { get; set; }
        public Nullable<int> GRADECODERF { get; set; }
        public string GRADENAMERF { get; set; }
        public string GRADEFULLNAMERF { get; set; }
        public string GRADEADDNAMEBCRF { get; set; }
        public string CARINSPECTCERTMODELRF { get; set; }
        public string EXHAUSTGASSIGNRF { get; set; }
        public string SERIESMODELRF { get; set; }
        public string ENGINEMODELNMRF { get; set; }
        public Nullable<int> TOTALENGINEDISPLACERF { get; set; }
        public Nullable<int> TTLENGINEDISPUNITCDRF { get; set; }
        public string TTLENGINEDISPUNITNMRF { get; set; }
        public Nullable<int> CMNNMENGINEDISPLACERF { get; set; }
        public Nullable<int> CMNNMENGDISPUNITCDRF { get; set; }
        public string CMNNMENGDISPUNITNMRF { get; set; }
        public string ROTORCNTRF { get; set; }
        public Nullable<int> PASSENGERCAPACITY1RF { get; set; }
        public Nullable<int> PASSENGERCAPACITY2RF { get; set; }
        public Nullable<int> MAXLOADINGCAPACITY1RF { get; set; }
        public Nullable<int> MAXLOADINGCAPACITY2RF { get; set; }
        public Nullable<int> VEHICLEWEIGHTRF { get; set; }
        public Nullable<int> GROSSVEHICLEWEIGHT1RF { get; set; }
        public Nullable<int> GROSSVEHICLEWEIGHT2RF { get; set; }
        public Nullable<int> CARLENGTH1RF { get; set; }
        public Nullable<int> CARLENGTH2RF { get; set; }
        public Nullable<int> CARLENGTH3RF { get; set; }
        public Nullable<int> CARHEIGHT1RF { get; set; }
        public Nullable<int> CARHEIGHT2RF { get; set; }
        public Nullable<int> CARHEIGHT3RF { get; set; }
        public Nullable<int> CARWIDTH1RF { get; set; }
        public Nullable<int> CARWIDTH2RF { get; set; }
        public Nullable<int> CARWIDTH3RF { get; set; }
        public Nullable<int> FFAXLEWEIGHTRF { get; set; }
        public Nullable<int> FRAXLEWEIGHTRF { get; set; }
        public Nullable<int> RFAXLEWEIGHTRF { get; set; }
        public Nullable<int> RRAXLEWEIGHTRF { get; set; }
        public string ENGINEMODELRF { get; set; }
        public Nullable<int> FUELCODERF { get; set; }
        public string FUELNAMERF { get; set; }
        public string ENGINEDISPLACERF { get; set; }
        public Nullable<int> DISPLACEMENTUNITCDRF { get; set; }
        public string DISPLACEMENTUNITNMRF { get; set; }
        public Nullable<double> FUELEFFICIENTRATERF { get; set; }
        public Nullable<int> HYBRIDDIVIDECDRF { get; set; }
        public string HYBRIDDIVIDENMRF { get; set; }
        public Nullable<int> HANDLEINFOCDRF { get; set; }
        public string HANDLEINFONMRF { get; set; }
        public Nullable<int> BRAKEINFOCDRF { get; set; }
        public string BRAKEINFONMRF { get; set; }
        public Nullable<int> WHEELDRIVEMETHODCDRF { get; set; }
        public string WHEELDRIVEMETHODNMRF { get; set; }
        public Nullable<int> GEARCDRF { get; set; }
        public string GEARNMRF { get; set; }
        public Nullable<int> NUMBEROFGEARRF { get; set; }
        public Nullable<int> SHIFTMETHODRF { get; set; }
        public string SHIFTMETHODNAMERF { get; set; }
        public Nullable<int> TMCODERF { get; set; }
        public string TMCODENAMERF { get; set; }
        public Nullable<int> ROOFSHAPECODERF { get; set; }
        public string ROOFSHAPENAMERF { get; set; }
        public Nullable<int> SHEETINFOCDRF { get; set; }
        public string SHEETINFONMRF { get; set; }
        public Nullable<int> EXGASSTRDLVLINFOCDRF { get; set; }
        public string EXGASSTRDLVLINFONMRF { get; set; }
        public Nullable<int> MILEMETERDISPVALUNITRF { get; set; }
        public Nullable<int> GENRECODERF { get; set; }
        public string GENRENAMERF { get; set; }
        public Nullable<int> BODYCOLORRF { get; set; }
        public string BODYCOLORNAMERF { get; set; }
        public string COLORCODERF { get; set; }
        public Nullable<int> COLORCDDUPDERIVEDNORF { get; set; }
        public string COLORNAME1RF { get; set; }
        public Nullable<int> BODYPAINTKINDCDRF { get; set; }
        public Nullable<int> TRFRBODYPAINTKINDCDRF { get; set; }
        public Nullable<int> LOWCONCEALEXISTRF { get; set; }
        public Nullable<int> HIGHFUNCTIONBPEXISTRF { get; set; }
        public Nullable<int> UNITECOLORCODERF { get; set; }
        public string TRIMCODERF { get; set; }
        public string TRIMNAMERF { get; set; }
        public Nullable<int> BLOCKILLUSTRATIONCDRF { get; set; }
        public Nullable<int> TWODILLUSTNORF { get; set; }
        public Nullable<int> THREEDILLUSTNORF { get; set; }
        public Nullable<int> BPINDEXOFFERFLAGRF { get; set; }
        public Nullable<int> EXCHINDEXOFFERFLAGRF { get; set; }
        public Nullable<int> BMPRBPINDEXOFFERFLAGRF { get; set; }
        public Nullable<int> FRMBPINDEXOFFERFLAGRF { get; set; }
        public Nullable<int> PARTSDATAOFFERFLAGRF { get; set; }
        public Nullable<int> FRBUMPERSAMECOLORCDRF { get; set; }
        public Nullable<int> FRBUMPERPAINTFILMCDRF { get; set; }
        public Nullable<int> FRBUMPERCRESTPTTNCDRF { get; set; }
        public Nullable<int> FRBUMPERHEATPROCCDRF { get; set; }
        public Nullable<int> FRBUMPERPFILMCNTCDRF { get; set; }
        public Nullable<int> RRBUMPERSAMECOLORCDRF { get; set; }
        public Nullable<int> RRBUMPERPAINTFILMCDRF { get; set; }
        public Nullable<int> RRBUMPERCRESTPTTNCDRF { get; set; }
        public Nullable<int> RRBUMPERHEATPROCCDRF { get; set; }
        public Nullable<int> RRBUMPERPFILMCNTCDRF { get; set; }
        public Nullable<int> TWOTONEDIVCDRF { get; set; }
        public Nullable<int> PAINTFILMKINDRF { get; set; }
        public Nullable<int> TWOTONEPAINTFILMKINDRF { get; set; }
        public Nullable<int> BOOTHUSEDIVCDRF { get; set; }
        public Nullable<int> RUSTPROOFWAXPAINTCDRF { get; set; }
        public Nullable<int> PAINTKINDRF { get; set; }
        public Nullable<int> HIGHFUNCBPDIVCDRF { get; set; }
        public Nullable<int> LOWCONCEALMENTDIVCDRF { get; set; }
        public string RPCOLORCODERF { get; set; }
        public Nullable<int> VEHICLEWEIGHT2RF { get; set; }
    }
}
