//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JxMobileWeb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class JXACCEGOINFURF
    {
        public long CREATEDATETIMERF { get; set; }
        public long UPDATEDATETIMERF { get; set; }
        public string ENTERPRISECODERF { get; set; }
        public System.Guid FILEHEADERGUIDRF { get; set; }
        public string UPDEMPLOYEECODERF { get; set; }
        public string UPDASSEMBLYID1RF { get; set; }
        public string UPDASSEMBLYID2RF { get; set; }
        public int LOGICALDELETECODERF { get; set; }
        public string SECTIONCODERF { get; set; }
        public int EGOILCODERF { get; set; }
        public string EGOILAPIGAUGERF { get; set; }
        public Nullable<int> EGOILAPIGAUGECDRF { get; set; }
        public string EGOILILSACGAUGERF { get; set; }
        public Nullable<int> EGOILILSACGAUGECDRF { get; set; }
        public string EGOILOTHERGAUGERF { get; set; }
        public string EGOILVISCOSITYRF { get; set; }
        public Nullable<int> EGOILVISCOSITYCDRF { get; set; }
        public string EGOILBASEOILRF { get; set; }
        public Nullable<int> EGOILBASEOILCDRF { get; set; }
        public string EGOILPRRF { get; set; }
        public Nullable<System.Guid> TAKEINIMAGECODERF { get; set; }
        public Nullable<int> FUELCODERF { get; set; }
        public Nullable<int> TURBOUSEDIVRF { get; set; }
        public string INPSECTIONCODERF { get; set; }
        public string EGOILMAKERRF { get; set; }
    }
}
