//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JxMobileWeb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class JXCUSTVTTLRF
    {
        public long CREATEDATETIMERF { get; set; }
        public long UPDATEDATETIMERF { get; set; }
        public string ENTERPRISECODERF { get; set; }
        public System.Guid FILEHEADERGUIDRF { get; set; }
        public string UPDEMPLOYEECODERF { get; set; }
        public string UPDASSEMBLYID1RF { get; set; }
        public string UPDASSEMBLYID2RF { get; set; }
        public int LOGICALDELETECODERF { get; set; }
        public string SECTIONCODERF { get; set; }
        public int CUSTOMERCODERF { get; set; }
        public Nullable<int> JXTTLUNITYMRF { get; set; }
        public Nullable<int> JXOILSPLYCTRF { get; set; }
        public Nullable<int> JXOILSPLYLSTDTRF { get; set; }
        public Nullable<int> JXBUYCTRF { get; set; }
        public Nullable<int> JXBUYRLSTDTRF { get; set; }
        public Nullable<int> JXVSTLSTDTRF { get; set; }
    }
}
