//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JxMobileWeb.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JXMobileDBContext : DbContext
    {
        public JXMobileDBContext()
            : base("name=JXMobileDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<vReportListForSearch> vReportListForSearch { get; set; }
        public DbSet<CARMAINRF> CARMAINRF { get; set; }
        public DbSet<CARSPECRF> CARSPECRF { get; set; }
        public DbSet<CUSTOMERRF> CUSTOMERRF { get; set; }
        public DbSet<JXACCEGOINFURF> JXACCEGOINFURF { get; set; }
        public DbSet<JXCUSTVTTLRF> JXCUSTVTTLRF { get; set; }
        public DbSet<JXNOMNGSETRF> JXNOMNGSETRF { get; set; }
        public DbSet<JXSLIPDETAILRF> JXSLIPDETAILRF { get; set; }
        public DbSet<JXSLIPHEDRRF> JXSLIPHEDRRF { get; set; }
    }
}
