//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JxMobileWeb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class JXNOMNGSETRF
    {
        public long CREATEDATETIMERF { get; set; }
        public long UPDATEDATETIMERF { get; set; }
        public string ENTERPRISECODERF { get; set; }
        public System.Guid FILEHEADERGUIDRF { get; set; }
        public string UPDEMPLOYEECODERF { get; set; }
        public string UPDASSEMBLYID1RF { get; set; }
        public string UPDASSEMBLYID2RF { get; set; }
        public int LOGICALDELETECODERF { get; set; }
        public string SECTIONCODERF { get; set; }
        public int JXNOCODERF { get; set; }
        public Nullable<long> NOPRESENTVALRF { get; set; }
        public Nullable<int> JXLASTYEARMONTHRF { get; set; }
        public Nullable<int> JXNORESETTIMINGDIVCDRF { get; set; }
    }
}
