//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JxMobileWeb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class JXSLIPDETAILRF
    {
        public long CREATEDATETIMERF { get; set; }
        public long UPDATEDATETIMERF { get; set; }
        public string ENTERPRISECODERF { get; set; }
        public System.Guid FILEHEADERGUIDRF { get; set; }
        public string UPDEMPLOYEECODERF { get; set; }
        public string UPDASSEMBLYID1RF { get; set; }
        public string UPDASSEMBLYID2RF { get; set; }
        public int LOGICALDELETECODERF { get; set; }
        public int JXESTMACPODRCDRF { get; set; }
        public string SLIPNORF { get; set; }
        public int JXDETAILNORF { get; set; }
        public int JXCARWASHCARECDRF { get; set; }
        public int JXGOODSGENRERF { get; set; }
        public int JXGOODSCODERF { get; set; }
        public string EGOILVISCOSITYRF { get; set; }
        public string BTTYSIZERF { get; set; }
        public string TIRESIZERF { get; set; }
        public Nullable<int> FUELCODERF { get; set; }
        public string JXPARTSNORF { get; set; }
        public string JXGOODSNAMERF { get; set; }
        public Nullable<double> JXGOODSCNTRF { get; set; }
        public Nullable<long> JXGOODSUNITPRICERF { get; set; }
        public Nullable<int> JXGOODSUNITPRCCORRCDRF { get; set; }
        public Nullable<long> JXGOODSPRICERF { get; set; }
        public Nullable<int> JXGOODSPRCCORRCDRF { get; set; }
        public Nullable<int> JXGOODSPRICEKNDRF { get; set; }
    }
}
