//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JxMobileWeb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class JXSLIPHEDRRF
    {
        public long CREATEDATETIMERF { get; set; }
        public long UPDATEDATETIMERF { get; set; }
        public string ENTERPRISECODERF { get; set; }
        public System.Guid FILEHEADERGUIDRF { get; set; }
        public string UPDEMPLOYEECODERF { get; set; }
        public string UPDASSEMBLYID1RF { get; set; }
        public string UPDASSEMBLYID2RF { get; set; }
        public int LOGICALDELETECODERF { get; set; }
        public int JXESTMACPODRCDRF { get; set; }
        public string SLIPNORF { get; set; }
        public Nullable<int> JXACALCFLGRF { get; set; }
        public Nullable<int> JXACCEPTDATERF { get; set; }
        public Nullable<int> JXACCEPTTIMERF { get; set; }
        public Nullable<int> JXWORKTIMERF { get; set; }
        public Nullable<int> JXWORKENDSCDLRF { get; set; }
        public Nullable<int> JXPAYMENTCDRF { get; set; }
        public Nullable<long> JXTOTALAMOUNTRF { get; set; }
        public Nullable<double> JXTAXRATERF { get; set; }
        public Nullable<int> JXFRACPRCCODERF { get; set; }
        public Nullable<int> MILEAGERF { get; set; }
        public string JXRPAGENTNAMERF { get; set; }
        public string JXRPAGENTMSGRF { get; set; }
        public Nullable<int> CARMNGNORF { get; set; }
        public Nullable<int> CUSTOMERCODERF { get; set; }
        public string NAMERF { get; set; }
        public string NAME2RF { get; set; }
        public string KANARF { get; set; }
        public string SEXNAMERF { get; set; }
        public Nullable<int> BIRTHDAYRF { get; set; }
        public string ADDRESS1RF { get; set; }
        public Nullable<int> ADDRESS2RF { get; set; }
        public string ADDRESS3RF { get; set; }
        public string ADDRESS4RF { get; set; }
        public string HOMETELNORF { get; set; }
        public string PORTABLETELNORF { get; set; }
        public string JXCARDMEMBERNAME1RF { get; set; }
        public string JXCARDMEMBERNAME2RF { get; set; }
        public string JXCARDMEMBERNAME3RF { get; set; }
        public string JXCARDMEMBERNAME4RF { get; set; }
        public string JXCARDMEMBERNAME5RF { get; set; }
        public Nullable<int> DMOUTCODERF { get; set; }
        public Nullable<int> MAILSENDCODERF { get; set; }
        public Nullable<int> NUMBERPLATE1CODERF { get; set; }
        public string NUMBERPLATE1NAMERF { get; set; }
        public string NUMBERPLATE2RF { get; set; }
        public string NUMBERPLATE3RF { get; set; }
        public Nullable<int> NUMBERPLATE4RF { get; set; }
        public Nullable<int> MAKERPARTSSRCHCODERF { get; set; }
        public Nullable<int> MAKERCODERF { get; set; }
        public Nullable<int> AIRAMAKERCODERF { get; set; }
        public string MAKERNAMERF { get; set; }
        public Nullable<int> MODELCODERF { get; set; }
        public Nullable<int> MODELSUBCODERF { get; set; }
        public string MODELNAMERF { get; set; }
        public Nullable<int> FIRSTENTRYDATENUMTYPRF { get; set; }
        public Nullable<int> ENTRYDATERF { get; set; }
        public Nullable<int> CIMATDATERF { get; set; }
        public byte[] JXSIGNIMGRF { get; set; }
    }
}
