//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JxMobileWeb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vReportListForSearch
    {
        public string ENTERPRISECODE { get; set; }
        public Nullable<int> CUSTOMERCODE { get; set; }
        public int CARMNGNO { get; set; }
        public string NUMBERPLATE { get; set; }
        public string MODELNAME { get; set; }
        public string CUSTNAME { get; set; }
        public string KANA { get; set; }
    }
}
